# Generated by Django 4.2.1 on 2023-06-11 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_members_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='last_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
